title-heading: false
#remote_theme: pages-themes/slate@v0.2.0

#remote_theme: pages-themes/minimal@v0.2.0 
#remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/

plugins:
- jekyll-remote-theme


